// <auto-generated />
namespace AMA.SchoolManagementSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class admin_in_school : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(admin_in_school));
        
        string IMigrationMetadata.Id
        {
            get { return "201805261823407_admin_in_school"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
